import { invoke } from "@tauri-apps/api/core";

export type VaultStatus = "not-created" | "locked" | "unlocked";
export type Note = { id: string; title: string; content: string; created_at: string; updated_at: string; folder?: string; tags: string[]; pinned: boolean; archived: boolean; deleted_at?: string };
export type NoteVersion = { id: number; note_id: string; title: string; content: string; folder?: string; tags: string[]; created_at: string; saved_at: string };
export type Attachment = { id: string; note_id: string; name: string; mime: string; size: number; created_at: string };
export type AttachmentPreview = { name: string; mime: string; data_base64: string };
export type OcrResult = { text: string; line_count: number };
export type BackupInfo = { note_count: number; attachment_count: number; created_at: string; valid: boolean };
export type SavedSearch = { id: string; name: string; query: string };
export type SecurityDiagnostics = { database_integrity: boolean; signed_build: boolean; recovery_enabled: boolean; pin_enabled: boolean; biometric_enabled: boolean; note_count: number; attachment_count: number };

export const vaultStatus = () => invoke<VaultStatus>("vault_status");
export const createVault = (password: string) => invoke("create_vault", { password });
export const unlockVault = (password: string) => invoke<Note[]>("unlock_vault", { password });
export const lockVault = () => invoke("lock_vault");
export const saveNote = (note: Note) => invoke<Note>("save_note", { note });
export const noteVersions = (noteId: string) => invoke<NoteVersion[]>("note_versions", { noteId });
export const restoreNoteVersion = (versionId: number, updatedAt: string) => invoke<Note>("restore_note_version", { versionId, updatedAt });
export const addAttachment = (noteId: string, path: string, createdAt: string) => invoke<Attachment>("add_attachment", { noteId, path, createdAt });
export const listAttachments = (noteId: string) => invoke<Attachment[]>("list_attachments", { noteId });
export const exportAttachment = (id: string, destination: string) => invoke("export_attachment", { id, destination });
export const removeAttachment = (id: string) => invoke("remove_attachment", { id });
export const previewAttachment = (id: string) => invoke<AttachmentPreview>("preview_attachment", { id });
export const recognizeAttachmentText = (id: string) => invoke<OcrResult>("recognize_attachment_text", { id });
export const importNoteFiles = (paths: string[], createdAt: string) => invoke<Note[]>("import_note_files", { paths, createdAt });
export const exportNoteMarkdown = (id: string, destination: string) => invoke("export_note_markdown", { id, destination });
export const exportSharedNote = (id: string, destination: string, password: string) => invoke("export_shared_note", { id, destination, password });
export const importSharedNote = (path: string, password: string, importedAt: string) => invoke<Note>("import_shared_note", { path, password, importedAt });
export const listSavedSearches = () => invoke<SavedSearch[]>("list_saved_searches");
export const saveSearch = (name: string, query: string) => invoke<SavedSearch>("save_search", { name, query });
export const deleteSavedSearch = (id: string) => invoke("delete_saved_search", { id });
export const securityDiagnostics = () => invoke<SecurityDiagnostics>("security_diagnostics");
export const deleteNote = (id: string) => invoke("delete_note", { id });
export const restoreNote = (id: string) => invoke("restore_note", { id });
export const permanentDeleteNote = (id: string) => invoke("permanent_delete_note", { id });
export const changePassword = (currentPassword: string, newPassword: string) => invoke("change_password", { currentPassword, newPassword });
export const createBackup = (destination: string) => invoke<string>("create_backup", { destination });
export const restoreBackup = (backupPath: string, password: string) => invoke<Note[]>("restore_backup", { backupPath, password });
export const validateBackup = (backupPath: string, password: string) => invoke<BackupInfo>("validate_backup", { backupPath, password });
export const generateRecoveryKey = (masterPassword: string) => invoke<string>("generate_recovery_key", { masterPassword });
export const recoveryKeyStatus = () => invoke<boolean>("recovery_key_status");
export const recoverVault = (recoveryCode: string, newPassword: string) => invoke<Note[]>("recover_vault", { recoveryCode, newPassword });
export const quickUnlockStatus = () => invoke<[boolean, boolean]>("quick_unlock_status");
export const enablePinUnlock = (masterPassword: string, pin: string) => invoke("enable_pin_unlock", { masterPassword, pin });
export const enableBiometricUnlock = (masterPassword: string) => invoke("enable_biometric_unlock", { masterPassword });
export const unlockPin = (pin: string) => invoke<Note[]>("unlock_pin", { pin });
export const unlockBiometric = () => invoke<Note[]>("unlock_biometric");
export const disableQuickUnlock = (masterPassword: string) => invoke("disable_quick_unlock", { masterPassword });
export const copySecret = (value: string) => invoke("copy_secret", { value });
export type ReminderRequest = { id: string; dueAt: number };
export const activityTimestamps = () => invoke<string[]>("activity_timestamps");
export const syncReminders = (reminders: ReminderRequest[]) => invoke("sync_reminders", { reminders });
